FROM apache/airflow:2.4.2-python3.9

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    && apt-get install -y openjdk-11-jdk \
    && apt-get install procps -y \
    && apt-get install -y ant \
	&& apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
# ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-arm64
RUN export JAVA_HOME

USER airflow
WORKDIR /home/airflow

COPY requirements_airflow.txt .

COPY .kaggle/ .kaggle/

RUN pip install --no-cache-dir -r requirements_airflow.txt
RUN python -m pip install --upgrade pip