FROM bitnami/spark:3.1.2
USER root

# Adicionar AWS S3 JARS
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.231/aws-java-sdk-bundle-1.12.231.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.231.jar
RUN curl https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.4/jets3t-0.9.4.jar --output /opt/bitnami/spark/jars/jets3t-0.9.4.jar

# Adicionar Azure Blob Storage JARS
RUN curl https://repo1.maven.org/maven2/com/microsoft/azure/azure-storage/8.6.0/azure-storage-8.6.0.jar --output /opt/bitnami/spark/jars/azure-storage-8.6.0.jar

COPY ./requirements_spark.txt /
RUN pip install -r /requirements_spark.txt